module Evergreen.Migrate.V16 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V13.Route
import Evergreen.V13.Types
import Evergreen.V16.Route
import Evergreen.V16.Types
import Lamdera.Migrations exposing (..)
import Result
import Set


frontendModel : Evergreen.V13.Types.FrontendModel -> ModelMigration Evergreen.V16.Types.FrontendModel Evergreen.V16.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V13.Types.BackendModel -> ModelMigration Evergreen.V16.Types.BackendModel Evergreen.V16.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V13.Types.FrontendMsg -> MsgMigration Evergreen.V16.Types.FrontendMsg Evergreen.V16.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V13.Types.ToBackend -> MsgMigration Evergreen.V16.Types.ToBackend Evergreen.V16.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V13.Types.BackendMsg -> MsgMigration Evergreen.V16.Types.BackendMsg Evergreen.V16.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V13.Types.ToFrontend -> MsgMigration Evergreen.V16.Types.ToFrontend Evergreen.V16.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V13.Types.BackendModel -> Evergreen.V16.Types.BackendModel
migrate_Types_BackendModel old =
    { publicCredits = old.publicCredits
    , emails = Set.empty
    }


migrate_Types_FrontendModel : Evergreen.V13.Types.FrontendModel -> Evergreen.V16.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = Evergreen.V16.Types.Inactive
    , maybeImportantNumber = Nothing
    }


migrate_Route_Route : Evergreen.V13.Route.Route -> Evergreen.V16.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V13.Route.Translate ->
            Evergreen.V16.Route.Translate

        Evergreen.V13.Route.Landing ->
            Evergreen.V16.Route.Landing

        Evergreen.V13.Route.BadRoute ->
            Evergreen.V16.Route.BadRoute


migrate_Types_BreakdownPart : Evergreen.V13.Types.BreakdownPart -> Evergreen.V16.Types.BreakdownPart
migrate_Types_BreakdownPart old =
    old


migrate_Types_CompletedRequest : Evergreen.V13.Types.CompletedRequest -> Evergreen.V16.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_FrontendMsg : Evergreen.V13.Types.FrontendMsg -> Evergreen.V16.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V13.Types.UrlClicked p0 ->
            Evergreen.V16.Types.UrlClicked p0

        Evergreen.V13.Types.UrlChanged p0 ->
            Evergreen.V16.Types.UrlChanged p0

        Evergreen.V13.Types.NoOpFrontendMsg ->
            Evergreen.V16.Types.NoOpFrontendMsg

        Evergreen.V13.Types.TextInputChanged p0 ->
            Evergreen.V16.Types.TextInputChanged p0

        Evergreen.V13.Types.SubmitText p0 ->
            Evergreen.V16.Types.SubmitText p0

        Evergreen.V13.Types.ShowExplanation p0 ->
            Evergreen.V16.Types.ShowExplanation (p0 |> migrate_Types_BreakdownPart)

        Evergreen.V13.Types.CycleLoadingAnimation ->
            Evergreen.V16.Types.CycleLoadingAnimation

        Evergreen.V13.Types.EditTranslation p0 ->
            Evergreen.V16.Types.EditTranslation p0

        Evergreen.V13.Types.GotoRoute p0 ->
            Evergreen.V16.Types.GotoRoute (p0 |> migrate_Route_Route)


migrate_Types_GptAssistError : Evergreen.V13.Types.GptAssistError -> Evergreen.V16.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V13.Types.OutOfCredits ->
            Evergreen.V16.Types.OutOfCredits

        Evergreen.V13.Types.ApiProtocolError p0 ->
            Evergreen.V16.Types.ApiProtocolError p0

        Evergreen.V13.Types.GptDecodeError p0 ->
            Evergreen.V16.Types.GptDecodeError p0

        Evergreen.V13.Types.GptExpressedError p0 ->
            Evergreen.V16.Types.GptExpressedError p0


migrate_Types_RequestState : Evergreen.V13.Types.RequestState -> Evergreen.V16.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V13.Types.Waiting p0 p1 ->
            Evergreen.V16.Types.Waiting p0 p1

        Evergreen.V13.Types.RequestComplete p0 ->
            Evergreen.V16.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_ToBackend : Evergreen.V13.Types.ToBackend -> Evergreen.V16.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V13.Types.NoOpToBackend ->
            Evergreen.V16.Types.NoOpToBackend

        Evergreen.V13.Types.SubmitTextForTranslation p0 ->
            Evergreen.V16.Types.SubmitTextForTranslation p0


migrate_Types_ToFrontend : Evergreen.V13.Types.ToFrontend -> Evergreen.V16.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V13.Types.NoOpToFrontend ->
            Evergreen.V16.Types.NoOpToFrontend

        Evergreen.V13.Types.TranslationResult p0 p1 ->
            Evergreen.V16.Types.TranslationResult p0
                (p1 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation)


migrate_Types_Translation : Evergreen.V13.Types.Translation -> Evergreen.V16.Types.Translation
migrate_Types_Translation old =
    old


migrate_Types_TranslationPageModel : Evergreen.V13.Types.TranslationPageModel -> Evergreen.V16.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V13.Types.InputtingText p0 ->
            Evergreen.V16.Types.InputtingText p0

        Evergreen.V13.Types.RequestSent p0 ->
            Evergreen.V16.Types.RequestSent (p0 |> migrate_Types_RequestState)
