module Evergreen.Migrate.V20 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V16.Types
import Evergreen.V20.Types
import Lamdera.Migrations exposing (..)
import Time


frontendModel : Evergreen.V16.Types.FrontendModel -> ModelMigration Evergreen.V20.Types.FrontendModel Evergreen.V20.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V16.Types.BackendModel -> ModelMigration Evergreen.V20.Types.BackendModel Evergreen.V20.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V16.Types.FrontendMsg -> MsgMigration Evergreen.V20.Types.FrontendMsg Evergreen.V20.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V16.Types.ToBackend -> MsgMigration Evergreen.V20.Types.ToBackend Evergreen.V20.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V16.Types.BackendMsg -> MsgMigration Evergreen.V20.Types.BackendMsg Evergreen.V20.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V16.Types.ToFrontend -> MsgMigration Evergreen.V20.Types.ToFrontend Evergreen.V20.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V16.Types.BackendModel -> Evergreen.V20.Types.BackendModel
migrate_Types_BackendModel old =
    { nowish = Time.millisToPosix 0
    , publicCredits = old.publicCredits
    , emails = old.emails
    , requests = []
    }


migrate_Types_BackendMsg : Evergreen.V16.Types.BackendMsg -> Evergreen.V20.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V16.Types.NoOpBackendMsg ->
            Evergreen.V20.Types.NoOpBackendMsg

        Evergreen.V16.Types.GptResponseReceived p0 p1 p2 ->
            Evergreen.V20.Types.GptResponseReceived p0 p1 p2

        Evergreen.V16.Types.AddPublicCredits ->
            Evergreen.V20.Types.AddPublicCredits
