module Evergreen.Migrate.V21 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V20.Route
import Evergreen.V20.Types
import Evergreen.V21.Route
import Evergreen.V21.Types
import Lamdera.Migrations exposing (..)
import List
import Result


frontendModel : Evergreen.V20.Types.FrontendModel -> ModelMigration Evergreen.V21.Types.FrontendModel Evergreen.V21.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V20.Types.BackendModel -> ModelMigration Evergreen.V21.Types.BackendModel Evergreen.V21.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V20.Types.FrontendMsg -> MsgMigration Evergreen.V21.Types.FrontendMsg Evergreen.V21.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V20.Types.ToBackend -> MsgMigration Evergreen.V21.Types.ToBackend Evergreen.V21.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V20.Types.BackendMsg -> MsgMigration Evergreen.V21.Types.BackendMsg Evergreen.V21.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V20.Types.ToFrontend -> MsgMigration Evergreen.V21.Types.ToFrontend Evergreen.V21.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V20.Types.BackendModel -> Evergreen.V21.Types.BackendModel
migrate_Types_BackendModel old =
    { nowish = old.nowish
    , publicCredits = old.publicCredits
    , emails = old.emails
    , requests = old.requests |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation ))
    }


migrate_Types_FrontendModel : Evergreen.V20.Types.FrontendModel -> Evergreen.V21.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = old.signupState |> migrate_Types_SignupState
    , maybeImportantNumber = old.maybeImportantNumber
    }


migrate_Route_Route : Evergreen.V20.Route.Route -> Evergreen.V21.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V20.Route.Translate ->
            Evergreen.V21.Route.Translate

        Evergreen.V20.Route.Landing ->
            Evergreen.V21.Route.Landing

        Evergreen.V20.Route.Admin ->
            Evergreen.V21.Route.Admin

        Evergreen.V20.Route.BadRoute ->
            Evergreen.V21.Route.BadRoute


migrate_Types_CompletedRequest : Evergreen.V20.Types.CompletedRequest -> Evergreen.V21.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_GptAssistError : Evergreen.V20.Types.GptAssistError -> Evergreen.V21.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V20.Types.OutOfCredits ->
            Evergreen.V21.Types.OutOfCredits

        Evergreen.V20.Types.ApiProtocolError p0 ->
            Evergreen.V21.Types.ApiProtocolError p0

        Evergreen.V20.Types.GptDecodeError p0 ->
            Evergreen.V21.Types.GptDecodeError p0

        Evergreen.V20.Types.GptExpressedError p0 ->
            Evergreen.V21.Types.GptExpressedError p0


migrate_Types_RequestState : Evergreen.V20.Types.RequestState -> Evergreen.V21.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V20.Types.Waiting p0 p1 ->
            Evergreen.V21.Types.Waiting p0 p1

        Evergreen.V20.Types.RequestComplete p0 ->
            Evergreen.V21.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_SignupState : Evergreen.V20.Types.SignupState -> Evergreen.V21.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V20.Types.Inactive ->
            Evergreen.V21.Types.Inactive

        Evergreen.V20.Types.Active p0 ->
            Evergreen.V21.Types.Active p0

        Evergreen.V20.Types.Submitting ->
            Evergreen.V21.Types.Submitting

        Evergreen.V20.Types.Submitted ->
            Evergreen.V21.Types.Submitted


migrate_Types_ToFrontend : Evergreen.V20.Types.ToFrontend -> Evergreen.V21.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V20.Types.NoOpToFrontend ->
            Evergreen.V21.Types.NoOpToFrontend

        Evergreen.V20.Types.TranslationResult p0 p1 ->
            Evergreen.V21.Types.TranslationResult p0
                (p1 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation)

        Evergreen.V20.Types.EmailSubmitAck ->
            Evergreen.V21.Types.EmailSubmitAck

        Evergreen.V20.Types.ImportantNumber p0 ->
            Evergreen.V21.Types.ImportantNumber p0


migrate_Types_Translation : Evergreen.V20.Types.Translation -> Evergreen.V21.Types.Translation
migrate_Types_Translation old =
    { breakdown = old.breakdown
    , translation = old.translation
    , translatedTo = Evergreen.V21.Types.English
    }


migrate_Types_TranslationPageModel : Evergreen.V20.Types.TranslationPageModel -> Evergreen.V21.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V20.Types.InputtingText p0 ->
            Evergreen.V21.Types.InputtingText p0

        Evergreen.V20.Types.RequestSent p0 ->
            Evergreen.V21.Types.RequestSent (p0 |> migrate_Types_RequestState)
