module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V23.Background.Types
import Evergreen.V23.Route
import Evergreen.V23.Types
import Evergreen.V25.Background.Types
import Evergreen.V25.Responsive
import Evergreen.V25.Route
import Evergreen.V25.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Result


frontendModel : Evergreen.V23.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V23.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V23.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V23.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V23.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V23.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V23.Types.FrontendModel -> Evergreen.V25.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , dProfile = Just <| Evergreen.V25.Responsive.Mobile
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = old.signupState |> migrate_Types_SignupState
    , maybeImportantNumber = old.maybeImportantNumber
    , animationTime = old.animationTime
    , backgroundModel = old.backgroundModel |> Maybe.map migrate_Background_Types_Model
    }


migrate_Background_Types_Model : Evergreen.V23.Background.Types.Model -> Evergreen.V25.Background.Types.Model
migrate_Background_Types_Model old =
    { seed = old.seed
    , startTime = old.startTime
    , pathsAcross = old.pathsAcross |> List.map migrate_Background_Types_PathAcross
    }


migrate_Background_Types_PathAcross : Evergreen.V23.Background.Types.PathAcross -> Evergreen.V25.Background.Types.PathAcross
migrate_Background_Types_PathAcross old =
    { yPathStart = old.yPathStart
    , sections = old.sections |> List.map migrate_Background_Types_PathSection
    , color =
        old.color
            |> (\rec -> rec)
    }


migrate_Background_Types_PathPiece : Evergreen.V23.Background.Types.PathPiece -> Evergreen.V25.Background.Types.PathPiece
migrate_Background_Types_PathPiece old =
    case old of
        Evergreen.V23.Background.Types.ElbowLeftToUp ->
            Evergreen.V25.Background.Types.ElbowLeftToUp

        Evergreen.V23.Background.Types.ElbowLeftToDown ->
            Evergreen.V25.Background.Types.ElbowLeftToDown

        Evergreen.V23.Background.Types.ElbowUpToRight ->
            Evergreen.V25.Background.Types.ElbowUpToRight

        Evergreen.V23.Background.Types.ElbowDownToRight ->
            Evergreen.V25.Background.Types.ElbowDownToRight

        Evergreen.V23.Background.Types.Right p0 ->
            Evergreen.V25.Background.Types.Right p0

        Evergreen.V23.Background.Types.Up p0 ->
            Evergreen.V25.Background.Types.Up p0

        Evergreen.V23.Background.Types.Down p0 ->
            Evergreen.V25.Background.Types.Down p0


migrate_Background_Types_PathSection : Evergreen.V23.Background.Types.PathSection -> Evergreen.V25.Background.Types.PathSection
migrate_Background_Types_PathSection old =
    { piece = old.piece |> migrate_Background_Types_PathPiece
    , endPointRelative = old.endPointRelative |> migrate_Background_Types_Point
    , startPointRelative = old.startPointRelative |> migrate_Background_Types_Point
    }


migrate_Background_Types_Point : Evergreen.V23.Background.Types.Point -> Evergreen.V25.Background.Types.Point
migrate_Background_Types_Point old =
    old


migrate_Route_Route : Evergreen.V23.Route.Route -> Evergreen.V25.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V23.Route.Translate ->
            Evergreen.V25.Route.Translate

        Evergreen.V23.Route.Landing ->
            Evergreen.V25.Route.Landing

        Evergreen.V23.Route.Admin ->
            Evergreen.V25.Route.Admin

        Evergreen.V23.Route.BadRoute ->
            Evergreen.V25.Route.BadRoute


migrate_Types_BreakdownPart : Evergreen.V23.Types.BreakdownPart -> Evergreen.V25.Types.BreakdownPart
migrate_Types_BreakdownPart old =
    old


migrate_Types_CompletedRequest : Evergreen.V23.Types.CompletedRequest -> Evergreen.V25.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_EnglishOrEstonian : Evergreen.V23.Types.EnglishOrEstonian -> Evergreen.V25.Types.EnglishOrEstonian
migrate_Types_EnglishOrEstonian old =
    case old of
        Evergreen.V23.Types.English ->
            Evergreen.V25.Types.English

        Evergreen.V23.Types.Estonian ->
            Evergreen.V25.Types.Estonian


migrate_Types_FrontendMsg : Evergreen.V23.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V23.Types.UrlClicked p0 ->
            Evergreen.V25.Types.UrlClicked p0

        Evergreen.V23.Types.UrlChanged p0 ->
            Evergreen.V25.Types.UrlChanged p0

        Evergreen.V23.Types.NoOpFrontendMsg ->
            Evergreen.V25.Types.NoOpFrontendMsg

        Evergreen.V23.Types.TextInputChanged p0 ->
            Evergreen.V25.Types.TextInputChanged p0

        Evergreen.V23.Types.SubmitText p0 ->
            Evergreen.V25.Types.SubmitText p0

        Evergreen.V23.Types.ShowExplanation p0 ->
            Evergreen.V25.Types.ShowExplanation (p0 |> migrate_Types_BreakdownPart)

        Evergreen.V23.Types.CycleLoadingAnimation ->
            Evergreen.V25.Types.CycleLoadingAnimation

        Evergreen.V23.Types.EditTranslation p0 ->
            Evergreen.V25.Types.EditTranslation p0

        Evergreen.V23.Types.GotoRoute p0 ->
            Evergreen.V25.Types.GotoRoute (p0 |> migrate_Route_Route)

        Evergreen.V23.Types.StartSignup ->
            Evergreen.V25.Types.StartSignup

        Evergreen.V23.Types.SubmitSignup p0 ->
            Evergreen.V25.Types.SubmitSignup p0

        Evergreen.V23.Types.SignupTextChanged p0 ->
            Evergreen.V25.Types.SignupTextChanged p0

        Evergreen.V23.Types.FetchImportantNumber ->
            Evergreen.V25.Types.FetchImportantNumber

        Evergreen.V23.Types.Animate p0 ->
            Evergreen.V25.Types.Animate p0


migrate_Types_GptAssistError : Evergreen.V23.Types.GptAssistError -> Evergreen.V25.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V23.Types.OutOfCredits ->
            Evergreen.V25.Types.OutOfCredits

        Evergreen.V23.Types.ApiProtocolError p0 ->
            Evergreen.V25.Types.ApiProtocolError p0

        Evergreen.V23.Types.GptDecodeError p0 ->
            Evergreen.V25.Types.GptDecodeError p0

        Evergreen.V23.Types.GptExpressedError p0 ->
            Evergreen.V25.Types.GptExpressedError p0


migrate_Types_RequestState : Evergreen.V23.Types.RequestState -> Evergreen.V25.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V23.Types.Waiting p0 p1 ->
            Evergreen.V25.Types.Waiting p0 p1

        Evergreen.V23.Types.RequestComplete p0 ->
            Evergreen.V25.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_SignupState : Evergreen.V23.Types.SignupState -> Evergreen.V25.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V23.Types.Inactive ->
            Evergreen.V25.Types.Inactive

        Evergreen.V23.Types.Active p0 ->
            Evergreen.V25.Types.Active p0

        Evergreen.V23.Types.Submitting ->
            Evergreen.V25.Types.Submitting

        Evergreen.V23.Types.Submitted ->
            Evergreen.V25.Types.Submitted


migrate_Types_Translation : Evergreen.V23.Types.Translation -> Evergreen.V25.Types.Translation
migrate_Types_Translation old =
    { breakdown = old.breakdown
    , translation = old.translation
    , translatedTo = old.translatedTo |> migrate_Types_EnglishOrEstonian
    }


migrate_Types_TranslationPageModel : Evergreen.V23.Types.TranslationPageModel -> Evergreen.V25.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V23.Types.InputtingText p0 ->
            Evergreen.V25.Types.InputtingText p0

        Evergreen.V23.Types.RequestSent p0 ->
            Evergreen.V25.Types.RequestSent (p0 |> migrate_Types_RequestState)
