module Evergreen.Migrate.V27 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V25.Background.Types
import Evergreen.V25.Responsive
import Evergreen.V25.Route
import Evergreen.V25.Types
import Evergreen.V27.Background.Types
import Evergreen.V27.Responsive
import Evergreen.V27.Route
import Evergreen.V27.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Result
import Time


frontendModel : Evergreen.V25.Types.FrontendModel -> ModelMigration Evergreen.V27.Types.FrontendModel Evergreen.V27.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V25.Types.BackendModel -> ModelMigration Evergreen.V27.Types.BackendModel Evergreen.V27.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V25.Types.FrontendMsg -> MsgMigration Evergreen.V27.Types.FrontendMsg Evergreen.V27.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V25.Types.ToBackend -> MsgMigration Evergreen.V27.Types.ToBackend Evergreen.V27.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V25.Types.BackendMsg -> MsgMigration Evergreen.V27.Types.BackendMsg Evergreen.V27.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V25.Types.ToFrontend -> MsgMigration Evergreen.V27.Types.ToFrontend Evergreen.V27.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V25.Types.FrontendModel -> Evergreen.V27.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , dProfile = old.dProfile |> Maybe.map migrate_Responsive_DisplayProfile
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = old.signupState |> migrate_Types_SignupState
    , maybeImportantNumber = old.maybeImportantNumber
    , animationTime = old.animationTime
    , backgroundModel = old.backgroundModel |> Maybe.map migrate_Background_Types_Model
    }


migrate_Background_Types_Model : Evergreen.V25.Background.Types.Model -> Evergreen.V27.Background.Types.Model
migrate_Background_Types_Model old =
    { seed = old.seed
    , animationTime = Time.millisToPosix 0
    , pathsAcross = old.pathsAcross |> List.map (\a -> ( migrate_pathAcross a, Nothing ))
    }


migrate_pathAcross : Evergreen.V25.Background.Types.PathAcross -> Evergreen.V27.Background.Types.PathAcross
migrate_pathAcross pathAcross =
    { yPathStart = pathAcross.yPathStart
    , sections =
        pathAcross.sections
            |> List.map migrate_section
    , color = pathAcross.color
    }


migrate_section : Evergreen.V25.Background.Types.PathSection -> Evergreen.V27.Background.Types.PathSection
migrate_section section =
    { piece = migrate_piece section.piece
    , endPointRelative = migrate_point section.endPointRelative
    , startPointRelative = migrate_point section.startPointRelative
    }


migrate_piece piece =
    case piece of
        Evergreen.V25.Background.Types.ElbowLeftToUp ->
            Evergreen.V27.Background.Types.ElbowLeftToUp

        Evergreen.V25.Background.Types.ElbowLeftToDown ->
            Evergreen.V27.Background.Types.ElbowLeftToDown

        Evergreen.V25.Background.Types.ElbowUpToRight ->
            Evergreen.V27.Background.Types.ElbowUpToRight

        Evergreen.V25.Background.Types.ElbowDownToRight ->
            Evergreen.V27.Background.Types.ElbowDownToRight

        Evergreen.V25.Background.Types.Right length ->
            Evergreen.V27.Background.Types.Right length

        Evergreen.V25.Background.Types.Up length ->
            Evergreen.V27.Background.Types.Up length

        Evergreen.V25.Background.Types.Down length ->
            Evergreen.V27.Background.Types.Down length


migrate_point point =
    { x = point.x, y = point.y }


migrate_Responsive_DisplayProfile : Evergreen.V25.Responsive.DisplayProfile -> Evergreen.V27.Responsive.DisplayProfile
migrate_Responsive_DisplayProfile old =
    case old of
        Evergreen.V25.Responsive.Desktop ->
            Evergreen.V27.Responsive.Desktop

        Evergreen.V25.Responsive.Mobile ->
            Evergreen.V27.Responsive.Mobile


migrate_Route_Route : Evergreen.V25.Route.Route -> Evergreen.V27.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V25.Route.Translate ->
            Evergreen.V27.Route.Translate

        Evergreen.V25.Route.Landing ->
            Evergreen.V27.Route.Landing

        Evergreen.V25.Route.Admin ->
            Evergreen.V27.Route.Admin

        Evergreen.V25.Route.BadRoute ->
            Evergreen.V27.Route.BadRoute


migrate_Types_BreakdownPart : Evergreen.V25.Types.BreakdownPart -> Evergreen.V27.Types.BreakdownPart
migrate_Types_BreakdownPart old =
    old


migrate_Types_CompletedRequest : Evergreen.V25.Types.CompletedRequest -> Evergreen.V27.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_EnglishOrEstonian : Evergreen.V25.Types.EnglishOrEstonian -> Evergreen.V27.Types.EnglishOrEstonian
migrate_Types_EnglishOrEstonian old =
    case old of
        Evergreen.V25.Types.English ->
            Evergreen.V27.Types.English

        Evergreen.V25.Types.Estonian ->
            Evergreen.V27.Types.Estonian


migrate_Types_FrontendMsg : Evergreen.V25.Types.FrontendMsg -> Evergreen.V27.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V25.Types.NoOpFrontendMsg ->
            Evergreen.V27.Types.NoOpFrontendMsg

        Evergreen.V25.Types.UrlClicked p0 ->
            Evergreen.V27.Types.UrlClicked p0

        Evergreen.V25.Types.UrlChanged p0 ->
            Evergreen.V27.Types.UrlChanged p0

        Evergreen.V25.Types.GotViewport p0 ->
            Evergreen.V27.Types.GotViewport p0

        Evergreen.V25.Types.Resize p0 p1 ->
            Evergreen.V27.Types.Resize p0 p1

        Evergreen.V25.Types.TextInputChanged p0 ->
            Evergreen.V27.Types.TextInputChanged p0

        Evergreen.V25.Types.SubmitText p0 ->
            Evergreen.V27.Types.SubmitText p0

        Evergreen.V25.Types.ShowExplanation p0 ->
            Evergreen.V27.Types.ShowExplanation (p0 |> migrate_Types_BreakdownPart)

        Evergreen.V25.Types.CycleLoadingAnimation ->
            Evergreen.V27.Types.CycleLoadingAnimation

        Evergreen.V25.Types.EditTranslation p0 ->
            Evergreen.V27.Types.EditTranslation p0

        Evergreen.V25.Types.GotoRoute p0 ->
            Evergreen.V27.Types.GotoRoute (p0 |> migrate_Route_Route)

        Evergreen.V25.Types.GotoTranslateAndFocus ->
            Evergreen.V27.Types.GotoTranslateAndFocus

        Evergreen.V25.Types.StartSignup ->
            Evergreen.V27.Types.StartSignup

        Evergreen.V25.Types.SubmitSignup p0 ->
            Evergreen.V27.Types.SubmitSignup p0

        Evergreen.V25.Types.SignupTextChanged p0 ->
            Evergreen.V27.Types.SignupTextChanged p0

        Evergreen.V25.Types.FetchImportantNumber ->
            Evergreen.V27.Types.FetchImportantNumber

        Evergreen.V25.Types.Animate p0 ->
            Evergreen.V27.Types.Animate p0


migrate_Types_GptAssistError : Evergreen.V25.Types.GptAssistError -> Evergreen.V27.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V25.Types.OutOfCredits ->
            Evergreen.V27.Types.OutOfCredits

        Evergreen.V25.Types.ApiProtocolError p0 ->
            Evergreen.V27.Types.ApiProtocolError p0

        Evergreen.V25.Types.GptDecodeError p0 ->
            Evergreen.V27.Types.GptDecodeError p0

        Evergreen.V25.Types.GptExpressedError p0 ->
            Evergreen.V27.Types.GptExpressedError p0


migrate_Types_RequestState : Evergreen.V25.Types.RequestState -> Evergreen.V27.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V25.Types.Waiting p0 p1 ->
            Evergreen.V27.Types.Waiting p0 p1

        Evergreen.V25.Types.RequestComplete p0 ->
            Evergreen.V27.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_SignupState : Evergreen.V25.Types.SignupState -> Evergreen.V27.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V25.Types.Inactive ->
            Evergreen.V27.Types.Inactive

        Evergreen.V25.Types.Active p0 ->
            Evergreen.V27.Types.Active p0

        Evergreen.V25.Types.Submitting ->
            Evergreen.V27.Types.Submitting

        Evergreen.V25.Types.Submitted ->
            Evergreen.V27.Types.Submitted


migrate_Types_Translation : Evergreen.V25.Types.Translation -> Evergreen.V27.Types.Translation
migrate_Types_Translation old =
    { breakdown = old.breakdown
    , translation = old.translation
    , translatedTo = old.translatedTo |> migrate_Types_EnglishOrEstonian
    }


migrate_Types_TranslationPageModel : Evergreen.V25.Types.TranslationPageModel -> Evergreen.V27.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V25.Types.InputtingText p0 ->
            Evergreen.V27.Types.InputtingText p0

        Evergreen.V25.Types.RequestSent p0 ->
            Evergreen.V27.Types.RequestSent (p0 |> migrate_Types_RequestState)
