module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V2.Route
import Evergreen.V2.Types
import Evergreen.V3.Route
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)
import Result


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , showExplainerSubtitle = True
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    }


migrate_Route_Route : Evergreen.V2.Route.Route -> Evergreen.V3.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V2.Route.Translate ->
            Evergreen.V3.Route.Translate

        Evergreen.V2.Route.History ->
            Evergreen.V3.Route.Translate

        Evergreen.V2.Route.Badroute ->
            Evergreen.V3.Route.BadRoute


migrate_Types_BreakdownPart : Evergreen.V2.Types.BreakdownPart -> Evergreen.V3.Types.BreakdownPart
migrate_Types_BreakdownPart old =
    old


migrate_Types_CompletedRequest : Evergreen.V2.Types.CompletedRequest -> Evergreen.V3.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.UrlClicked p0 ->
            Evergreen.V3.Types.UrlClicked p0

        Evergreen.V2.Types.UrlChanged p0 ->
            Evergreen.V3.Types.UrlChanged p0

        Evergreen.V2.Types.NoOpFrontendMsg ->
            Evergreen.V3.Types.NoOpFrontendMsg

        Evergreen.V2.Types.TextInputChanged p0 ->
            Evergreen.V3.Types.TextInputChanged p0

        Evergreen.V2.Types.SubmitText p0 ->
            Evergreen.V3.Types.SubmitText p0

        Evergreen.V2.Types.ShowExplanation p0 ->
            Evergreen.V3.Types.ShowExplanation (p0 |> migrate_Types_BreakdownPart)

        Evergreen.V2.Types.CycleLoadingAnimation ->
            Evergreen.V3.Types.CycleLoadingAnimation

        Evergreen.V2.Types.EditTranslation p0 ->
            Evergreen.V3.Types.EditTranslation p0


migrate_Types_GptAssistError : Evergreen.V2.Types.GptAssistError -> Evergreen.V3.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V2.Types.OutOfCredits ->
            Evergreen.V3.Types.OutOfCredits

        Evergreen.V2.Types.ApiProtocolError p0 ->
            Evergreen.V3.Types.ApiProtocolError p0

        Evergreen.V2.Types.GptDecodeError p0 ->
            Evergreen.V3.Types.GptDecodeError p0

        Evergreen.V2.Types.GptExpressedError p0 ->
            Evergreen.V3.Types.GptExpressedError p0


migrate_Types_RequestState : Evergreen.V2.Types.RequestState -> Evergreen.V3.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V2.Types.Waiting p0 p1 ->
            Evergreen.V3.Types.Waiting p0 p1

        Evergreen.V2.Types.RequestComplete p0 ->
            Evergreen.V3.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_Translation : Evergreen.V2.Types.Translation -> Evergreen.V3.Types.Translation
migrate_Types_Translation old =
    old


migrate_Types_TranslationPageModel : Evergreen.V2.Types.TranslationPageModel -> Evergreen.V3.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V2.Types.InputtingText p0 ->
            Evergreen.V3.Types.InputtingText p0

        Evergreen.V2.Types.RequestSent p0 ->
            Evergreen.V3.Types.RequestSent (p0 |> migrate_Types_RequestState)
