module Evergreen.Migrate.V33 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V28.Background.Types
import Evergreen.V28.Responsive
import Evergreen.V28.Route
import Evergreen.V28.Types
import Evergreen.V33.Background.Types
import Evergreen.V33.Responsive
import Evergreen.V33.Route
import Evergreen.V33.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Result
import Set


frontendModel : Evergreen.V28.Types.FrontendModel -> ModelMigration Evergreen.V33.Types.FrontendModel Evergreen.V33.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V28.Types.BackendModel -> ModelMigration Evergreen.V33.Types.BackendModel Evergreen.V33.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V28.Types.FrontendMsg -> MsgMigration Evergreen.V33.Types.FrontendMsg Evergreen.V33.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V28.Types.ToBackend -> MsgMigration Evergreen.V33.Types.ToBackend Evergreen.V33.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V28.Types.BackendMsg -> MsgMigration Evergreen.V33.Types.BackendMsg Evergreen.V33.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V28.Types.ToFrontend -> MsgMigration Evergreen.V33.Types.ToFrontend Evergreen.V33.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V28.Types.BackendModel -> Evergreen.V33.Types.BackendModel
migrate_Types_BackendModel old =
    { nowish = old.nowish
    , publicCredits = old.publicCredits
    , emails_backup = old.emails
    , emailsWithConsents =
        old.emails
            |> Set.toList
            |> List.map
                (\email ->
                    Evergreen.V33.Types.EmailAndConsents
                        email
                        [ "hearing about major new features for Eestisse when they come out" ]
                )
    , requests = old.requests |> List.map (\( t1, t2, t3 ) -> ( t1, t2, t3 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation ))
    }


migrate_Types_FrontendModel : Evergreen.V28.Types.FrontendModel -> Evergreen.V33.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , dProfile = old.dProfile |> Maybe.map migrate_Responsive_DisplayProfile
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = old.signupState |> migrate_Types_SignupState
    , maybeImportantNumbers = Nothing
    , animationTime = old.animationTime
    , backgroundModel = old.backgroundModel |> Maybe.map migrate_Background_Types_Model
    }


migrate_Background_Types_Model : Evergreen.V28.Background.Types.Model -> Evergreen.V33.Background.Types.Model
migrate_Background_Types_Model old =
    { seed = old.seed
    , animationTime = old.animationTime
    , pathsAcross = old.pathsAcross |> List.map (Tuple.mapBoth migrate_Background_Types_PathAcross (Maybe.map migrate_Background_Types_PathAcrossAnimationState))
    }


migrate_Background_Types_PathAcross : Evergreen.V28.Background.Types.PathAcross -> Evergreen.V33.Background.Types.PathAcross
migrate_Background_Types_PathAcross old =
    { yPathStart = old.yPathStart
    , sections = old.sections |> List.map migrate_Background_Types_PathSection
    , color =
        old.color
            |> (\rec -> rec)
    }


migrate_Background_Types_PathAcrossAnimationState : Evergreen.V28.Background.Types.PathAcrossAnimationState -> Evergreen.V33.Background.Types.PathAcrossAnimationState
migrate_Background_Types_PathAcrossAnimationState old =
    { pathAcrossTarget = old.pathAcrossTarget |> migrate_Background_Types_PathAcross
    , animationStart = old.animationStart
    }


migrate_Background_Types_PathPiece : Evergreen.V28.Background.Types.PathPiece -> Evergreen.V33.Background.Types.PathPiece
migrate_Background_Types_PathPiece old =
    case old of
        Evergreen.V28.Background.Types.ElbowLeftToUp ->
            Evergreen.V33.Background.Types.ElbowLeftToUp

        Evergreen.V28.Background.Types.ElbowLeftToDown ->
            Evergreen.V33.Background.Types.ElbowLeftToDown

        Evergreen.V28.Background.Types.ElbowUpToRight ->
            Evergreen.V33.Background.Types.ElbowUpToRight

        Evergreen.V28.Background.Types.ElbowDownToRight ->
            Evergreen.V33.Background.Types.ElbowDownToRight

        Evergreen.V28.Background.Types.Right p0 ->
            Evergreen.V33.Background.Types.Right p0

        Evergreen.V28.Background.Types.Up p0 ->
            Evergreen.V33.Background.Types.Up p0

        Evergreen.V28.Background.Types.Down p0 ->
            Evergreen.V33.Background.Types.Down p0


migrate_Background_Types_PathSection : Evergreen.V28.Background.Types.PathSection -> Evergreen.V33.Background.Types.PathSection
migrate_Background_Types_PathSection old =
    { piece = old.piece |> migrate_Background_Types_PathPiece
    , endPointRelative = old.endPointRelative |> migrate_Background_Types_Point
    , startPointRelative = old.startPointRelative |> migrate_Background_Types_Point
    }


migrate_Background_Types_Point : Evergreen.V28.Background.Types.Point -> Evergreen.V33.Background.Types.Point
migrate_Background_Types_Point old =
    old


migrate_Responsive_DisplayProfile : Evergreen.V28.Responsive.DisplayProfile -> Evergreen.V33.Responsive.DisplayProfile
migrate_Responsive_DisplayProfile old =
    case old of
        Evergreen.V28.Responsive.Desktop ->
            Evergreen.V33.Responsive.Desktop

        Evergreen.V28.Responsive.Mobile ->
            Evergreen.V33.Responsive.Mobile


migrate_Route_Route : Evergreen.V28.Route.Route -> Evergreen.V33.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V28.Route.Translate ->
            Evergreen.V33.Route.Translate

        Evergreen.V28.Route.Landing ->
            Evergreen.V33.Route.Landing

        Evergreen.V28.Route.Admin ->
            Evergreen.V33.Route.Admin

        Evergreen.V28.Route.BadRoute ->
            Evergreen.V33.Route.BadRoute


migrate_Types_BreakdownPart : Evergreen.V28.Types.BreakdownPart -> Evergreen.V33.Types.BreakdownPart
migrate_Types_BreakdownPart old =
    old


migrate_Types_CompletedRequest : Evergreen.V28.Types.CompletedRequest -> Evergreen.V33.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_EnglishOrEstonian : Evergreen.V28.Types.EnglishOrEstonian -> Evergreen.V33.Types.EnglishOrEstonian
migrate_Types_EnglishOrEstonian old =
    case old of
        Evergreen.V28.Types.English ->
            Evergreen.V33.Types.English

        Evergreen.V28.Types.Estonian ->
            Evergreen.V33.Types.Estonian


migrate_Types_FrontendMsg : Evergreen.V28.Types.FrontendMsg -> Evergreen.V33.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V28.Types.NoOpFrontendMsg ->
            Evergreen.V33.Types.NoOpFrontendMsg

        Evergreen.V28.Types.UrlClicked p0 ->
            Evergreen.V33.Types.UrlClicked p0

        Evergreen.V28.Types.UrlChanged p0 ->
            Evergreen.V33.Types.UrlChanged p0

        Evergreen.V28.Types.GotViewport p0 ->
            Evergreen.V33.Types.GotViewport p0

        Evergreen.V28.Types.Resize p0 p1 ->
            Evergreen.V33.Types.Resize p0 p1

        Evergreen.V28.Types.TextInputChanged p0 ->
            Evergreen.V33.Types.TextInputChanged p0

        Evergreen.V28.Types.SubmitText p0 ->
            Evergreen.V33.Types.SubmitText p0

        Evergreen.V28.Types.ShowExplanation p0 ->
            Evergreen.V33.Types.ShowExplanation (p0 |> migrate_Types_BreakdownPart)

        Evergreen.V28.Types.CycleLoadingAnimation ->
            Evergreen.V33.Types.CycleLoadingAnimation

        Evergreen.V28.Types.EditTranslation p0 ->
            Evergreen.V33.Types.EditTranslation p0

        Evergreen.V28.Types.GotoRoute p0 ->
            Evergreen.V33.Types.GotoRoute (p0 |> migrate_Route_Route)

        Evergreen.V28.Types.GotoTranslateAndFocus ->
            Evergreen.V33.Types.GotoTranslate_FocusAndClear

        Evergreen.V28.Types.StartSignup ->
            Evergreen.V33.Types.StartSignup

        Evergreen.V28.Types.SubmitSignup p0 ->
            Evergreen.V33.Types.SubmitSignupClicked <|
                Evergreen.V33.Types.SignupFormModel
                    p0
                    True
                    False

        Evergreen.V28.Types.SignupTextChanged p0 ->
            Evergreen.V33.Types.SignupFormChanged <|
                Evergreen.V33.Types.SignupFormModel
                    p0
                    True
                    False

        Evergreen.V28.Types.FetchImportantNumber ->
            Evergreen.V33.Types.FetchImportantNumber

        Evergreen.V28.Types.Animate p0 ->
            Evergreen.V33.Types.Animate p0

        Evergreen.V28.Types.FiddleRandomBackroundPath p0 ->
            Evergreen.V33.Types.FiddleRandomBackroundPath p0


migrate_Types_GptAssistError : Evergreen.V28.Types.GptAssistError -> Evergreen.V33.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V28.Types.OutOfCredits ->
            Evergreen.V33.Types.OutOfCredits

        Evergreen.V28.Types.ApiProtocolError p0 ->
            Evergreen.V33.Types.ApiProtocolError (p0 |> migrate_Types_ProtocolError)

        Evergreen.V28.Types.GptDecodeError p0 ->
            Evergreen.V33.Types.GptDecodeError p0

        Evergreen.V28.Types.GptExpressedError p0 ->
            Evergreen.V33.Types.GptExpressedError p0


migrate_Types_ProtocolError : Evergreen.V28.Types.ProtocolError -> Evergreen.V33.Types.ProtocolError
migrate_Types_ProtocolError old =
    case old of
        Evergreen.V28.Types.RateLimited ->
            Evergreen.V33.Types.RateLimited

        Evergreen.V28.Types.HttpError p0 ->
            Evergreen.V33.Types.HttpError p0


migrate_Types_RequestState : Evergreen.V28.Types.RequestState -> Evergreen.V33.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V28.Types.Waiting p0 p1 ->
            Evergreen.V33.Types.Waiting p0 p1

        Evergreen.V28.Types.RequestComplete p0 ->
            Evergreen.V33.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_SignupState : Evergreen.V28.Types.SignupState -> Evergreen.V33.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V28.Types.Inactive ->
            Evergreen.V33.Types.Inactive

        Evergreen.V28.Types.Active p0 ->
            Evergreen.V33.Types.Active <|
                Evergreen.V33.Types.SignupFormModel p0 True False

        Evergreen.V28.Types.Submitting ->
            Evergreen.V33.Types.Submitting

        Evergreen.V28.Types.Submitted ->
            Evergreen.V33.Types.Submitted


migrate_Types_ToBackend : Evergreen.V28.Types.ToBackend -> Evergreen.V33.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V28.Types.NoOpToBackend ->
            Evergreen.V33.Types.NoOpToBackend

        Evergreen.V28.Types.SubmitTextForTranslation p0 ->
            Evergreen.V33.Types.SubmitTextForTranslation p0

        Evergreen.V28.Types.SubmitEmail p0 ->
            Evergreen.V33.Types.SubmitSignup <|
                Evergreen.V33.Types.SignupFormModel p0 True False

        Evergreen.V28.Types.RequestImportantNumber ->
            Evergreen.V33.Types.RequestImportantNumber


migrate_Types_ToFrontend : Evergreen.V28.Types.ToFrontend -> Evergreen.V33.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V28.Types.NoOpToFrontend ->
            Evergreen.V33.Types.NoOpToFrontend

        Evergreen.V28.Types.TranslationResult p0 p1 ->
            Evergreen.V33.Types.TranslationResult p0
                (p1 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation)

        Evergreen.V28.Types.EmailSubmitAck ->
            Evergreen.V33.Types.EmailSubmitAck

        Evergreen.V28.Types.ImportantNumber p0 ->
            Evergreen.V33.Types.ImportantNumbers [ ( "", p0 ) ]


migrate_Types_Translation : Evergreen.V28.Types.Translation -> Evergreen.V33.Types.Translation
migrate_Types_Translation old =
    { breakdown = old.breakdown
    , translation = old.translation
    , translatedTo = old.translatedTo |> migrate_Types_EnglishOrEstonian
    }


migrate_Types_TranslationPageModel : Evergreen.V28.Types.TranslationPageModel -> Evergreen.V33.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V28.Types.InputtingText p0 ->
            Evergreen.V33.Types.InputtingText p0

        Evergreen.V28.Types.RequestSent p0 ->
            Evergreen.V33.Types.RequestSent (p0 |> migrate_Types_RequestState)
