module Evergreen.Migrate.V39 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V37.Background.Types
import Evergreen.V37.Point
import Evergreen.V37.Responsive
import Evergreen.V37.Route
import Evergreen.V37.Types
import Evergreen.V39.Background.Types
import Evergreen.V39.Point
import Evergreen.V39.Responsive
import Evergreen.V39.Route
import Evergreen.V39.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Result


frontendModel : Evergreen.V37.Types.FrontendModel -> ModelMigration Evergreen.V39.Types.FrontendModel Evergreen.V39.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V37.Types.BackendModel -> ModelMigration Evergreen.V39.Types.BackendModel Evergreen.V39.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V37.Types.FrontendMsg -> MsgMigration Evergreen.V39.Types.FrontendMsg Evergreen.V39.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V37.Types.ToBackend -> MsgMigration Evergreen.V39.Types.ToBackend Evergreen.V39.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V37.Types.BackendMsg -> MsgMigration Evergreen.V39.Types.BackendMsg Evergreen.V39.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V37.Types.ToFrontend -> MsgMigration Evergreen.V39.Types.ToFrontend Evergreen.V39.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V37.Types.FrontendModel -> Evergreen.V39.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , dProfile = old.dProfile |> Maybe.map migrate_Responsive_DisplayProfile
    , translationPageModel = old.translationPageModel |> migrate_Types_TranslationPageModel
    , signupState = old.signupState |> migrate_Types_SignupState
    , maybeAdminData = Nothing
    , animationTime = old.animationTime
    , backgroundModel = old.backgroundModel |> Maybe.map migrate_Background_Types_Model
    , publicCredits = old.publicCredits
    , showCreditCounterTooltip = old.showCreditCounterTooltip
    , creditsCounterAnimationState = old.creditsCounterAnimationState
    }


migrate_Background_Types_Model : Evergreen.V37.Background.Types.Model -> Evergreen.V39.Background.Types.Model
migrate_Background_Types_Model old =
    { seed = old.seed
    , animationTime = old.animationTime
    , pathsAcross = old.pathsAcross |> List.map (Tuple.mapBoth migrate_Background_Types_PathAcross (Maybe.map migrate_Background_Types_PathAcrossAnimationState))
    }


migrate_Background_Types_PathAcross : Evergreen.V37.Background.Types.PathAcross -> Evergreen.V39.Background.Types.PathAcross
migrate_Background_Types_PathAcross old =
    { yPathStart = old.yPathStart
    , sections = old.sections |> List.map migrate_Background_Types_PathSection
    , color =
        old.color
            |> (\rec -> rec)
    }


migrate_Background_Types_PathAcrossAnimationState : Evergreen.V37.Background.Types.PathAcrossAnimationState -> Evergreen.V39.Background.Types.PathAcrossAnimationState
migrate_Background_Types_PathAcrossAnimationState old =
    { pathAcrossTarget = old.pathAcrossTarget |> migrate_Background_Types_PathAcross
    , animationStart = old.animationStart
    }


migrate_Background_Types_PathPiece : Evergreen.V37.Background.Types.PathPiece -> Evergreen.V39.Background.Types.PathPiece
migrate_Background_Types_PathPiece old =
    case old of
        Evergreen.V37.Background.Types.ElbowLeftToUp ->
            Evergreen.V39.Background.Types.ElbowLeftToUp

        Evergreen.V37.Background.Types.ElbowLeftToDown ->
            Evergreen.V39.Background.Types.ElbowLeftToDown

        Evergreen.V37.Background.Types.ElbowUpToRight ->
            Evergreen.V39.Background.Types.ElbowUpToRight

        Evergreen.V37.Background.Types.ElbowDownToRight ->
            Evergreen.V39.Background.Types.ElbowDownToRight

        Evergreen.V37.Background.Types.Right p0 ->
            Evergreen.V39.Background.Types.Right p0

        Evergreen.V37.Background.Types.Up p0 ->
            Evergreen.V39.Background.Types.Up p0

        Evergreen.V37.Background.Types.Down p0 ->
            Evergreen.V39.Background.Types.Down p0


migrate_Background_Types_PathSection : Evergreen.V37.Background.Types.PathSection -> Evergreen.V39.Background.Types.PathSection
migrate_Background_Types_PathSection old =
    { piece = old.piece |> migrate_Background_Types_PathPiece
    , endPointRelative = old.endPointRelative |> migrate_Point_Point
    , startPointRelative = old.startPointRelative |> migrate_Point_Point
    }


migrate_Point_Point : Evergreen.V37.Point.Point -> Evergreen.V39.Point.Point
migrate_Point_Point old =
    old


migrate_Responsive_DisplayProfile : Evergreen.V37.Responsive.DisplayProfile -> Evergreen.V39.Responsive.DisplayProfile
migrate_Responsive_DisplayProfile old =
    case old of
        Evergreen.V37.Responsive.Desktop ->
            Evergreen.V39.Responsive.Desktop

        Evergreen.V37.Responsive.Mobile ->
            Evergreen.V39.Responsive.Mobile


migrate_Route_Route : Evergreen.V37.Route.Route -> Evergreen.V39.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V37.Route.Translate ->
            Evergreen.V39.Route.Translate

        Evergreen.V37.Route.Landing ->
            Evergreen.V39.Route.Landing

        Evergreen.V37.Route.Admin ->
            Evergreen.V39.Route.Admin

        Evergreen.V37.Route.BadRoute ->
            Evergreen.V39.Route.BadRoute


migrate_Types_CompletedRequest : Evergreen.V37.Types.CompletedRequest -> Evergreen.V39.Types.CompletedRequest
migrate_Types_CompletedRequest old =
    { inputText = old.inputText
    , translationResult = old.translationResult |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation
    , maybeSelectedBreakdownPart = old.maybeSelectedBreakdownPart
    }


migrate_Types_EnglishOrEstonian : Evergreen.V37.Types.EnglishOrEstonian -> Evergreen.V39.Types.EnglishOrEstonian
migrate_Types_EnglishOrEstonian old =
    case old of
        Evergreen.V37.Types.English ->
            Evergreen.V39.Types.English

        Evergreen.V37.Types.Estonian ->
            Evergreen.V39.Types.Estonian


migrate_Types_GeneralData : Evergreen.V37.Types.GeneralData -> Evergreen.V39.Types.GeneralData
migrate_Types_GeneralData old =
    old


migrate_Types_GptAssistError : Evergreen.V37.Types.GptAssistError -> Evergreen.V39.Types.GptAssistError
migrate_Types_GptAssistError old =
    case old of
        Evergreen.V37.Types.OutOfCredits ->
            Evergreen.V39.Types.OutOfCredits

        Evergreen.V37.Types.ApiProtocolError p0 ->
            Evergreen.V39.Types.ApiProtocolError (p0 |> migrate_Types_ProtocolError)

        Evergreen.V37.Types.GptDecodeError p0 ->
            Evergreen.V39.Types.GptDecodeError p0

        Evergreen.V37.Types.GptExpressedError p0 ->
            Evergreen.V39.Types.GptExpressedError p0


migrate_Types_ProtocolError : Evergreen.V37.Types.ProtocolError -> Evergreen.V39.Types.ProtocolError
migrate_Types_ProtocolError old =
    case old of
        Evergreen.V37.Types.RateLimited ->
            Evergreen.V39.Types.RateLimited

        Evergreen.V37.Types.HttpError p0 ->
            Evergreen.V39.Types.HttpError p0


migrate_Types_RequestState : Evergreen.V37.Types.RequestState -> Evergreen.V39.Types.RequestState
migrate_Types_RequestState old =
    case old of
        Evergreen.V37.Types.Waiting p0 p1 ->
            Evergreen.V39.Types.Waiting p0 p1

        Evergreen.V37.Types.RequestComplete p0 ->
            Evergreen.V39.Types.RequestComplete (p0 |> migrate_Types_CompletedRequest)


migrate_Types_SignupFormModel : Evergreen.V37.Types.SignupFormModel -> Evergreen.V39.Types.SignupFormModel
migrate_Types_SignupFormModel old =
    old


migrate_Types_SignupState : Evergreen.V37.Types.SignupState -> Evergreen.V39.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V37.Types.Inactive ->
            Evergreen.V39.Types.Inactive

        Evergreen.V37.Types.Active p0 ->
            Evergreen.V39.Types.Active (p0 |> migrate_Types_SignupFormModel)

        Evergreen.V37.Types.Submitting ->
            Evergreen.V39.Types.Submitting

        Evergreen.V37.Types.Submitted ->
            Evergreen.V39.Types.Submitted


migrate_Types_ToFrontend : Evergreen.V37.Types.ToFrontend -> Evergreen.V39.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V37.Types.NoOpToFrontend ->
            Evergreen.V39.Types.NoOpToFrontend

        Evergreen.V37.Types.TranslationResult p0 p1 ->
            Evergreen.V39.Types.TranslationResult p0
                (p1 |> Result.mapError migrate_Types_GptAssistError >> Result.map migrate_Types_Translation)

        Evergreen.V37.Types.EmailSubmitAck ->
            Evergreen.V39.Types.EmailSubmitAck

        Evergreen.V37.Types.ImportantNumbers p0 ->
            Evergreen.V39.Types.NoOpToFrontend

        Evergreen.V37.Types.GeneralDataMsg p0 ->
            Evergreen.V39.Types.GeneralDataMsg (p0 |> migrate_Types_GeneralData)

        Evergreen.V37.Types.CreditsUpdated p0 ->
            Evergreen.V39.Types.CreditsUpdated p0


migrate_Types_Translation : Evergreen.V37.Types.Translation -> Evergreen.V39.Types.Translation
migrate_Types_Translation old =
    { breakdown = old.breakdown
    , translation = old.translation
    , translatedTo = old.translatedTo |> migrate_Types_EnglishOrEstonian
    }


migrate_Types_TranslationPageModel : Evergreen.V37.Types.TranslationPageModel -> Evergreen.V39.Types.TranslationPageModel
migrate_Types_TranslationPageModel old =
    case old of
        Evergreen.V37.Types.InputtingText p0 ->
            Evergreen.V39.Types.InputtingText p0

        Evergreen.V37.Types.RequestSent p0 ->
            Evergreen.V39.Types.RequestSent (p0 |> migrate_Types_RequestState)
